### ISSUE TITLE
“Could not connect to thrift client on port 9090” when exec the step 12

### ISSUE THREAD

**Issue by Natsuyu** [AmedeoSapio/DAIET-HotNets17#4]
hi,
when I do the step12 as readme, I run "sudo screen -r bmv2" and "simple_switch_CLI \
    < /Testbed/DAIET/tests/single_switch/commands.txt" in command line. It occurs error:

Could not connect to thrift client on port 9090
Make sure the switch is running and that you have the right port

<img width="638" alt="image" src="https://user-images.githubusercontent.com/11704145/54875784-1513bf80-4e40-11e9-8b05-b5eb2d00e97b.png">
how can I fix it?

thx

**Comment by AmedeoSapio** [comment]
What is the output of step 9?
